### PR TITLE
fix: Ignore task definition fields that are Describe outputs, but not Register inputs

### LINKED ISSUE #22: * UnexpectedParameter: Unexpected key <name> errors
Workflow created using [ suggested AWS actions/starter-workflows](https://github.com/actions/starter-workflows/blob/master/ci/aws.yml)

On this step:

```
    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: sample-app
        image: ${{ steps.build-image.outputs.image }}
```

I replaced the version to the last version

```
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1.0.1
```

and I have the task-definition.json file on repository correctly (copied from json tab, this step works fine)

But on the following step, that uses amazon-ecs-deploy-task-definition, I get this error:

```
 Deploy Amazon ECS task definition0s
##[error]Node run failed with exit code 1
Run aws-actions/amazon-ecs-deploy-task-definition@v1.0.1
##[error]There were 5 validation errors:
* UnexpectedParameter: Unexpected key 'compatibilities' found in params
* UnexpectedParameter: Unexpected key 'taskDefinitionArn' found in params
* UnexpectedParameter: Unexpected key 'requiresAttributes' found in params
* UnexpectedParameter: Unexpected key 'revision' found in params
* UnexpectedParameter: Unexpected key 'status' found in params
##[error]Node run failed with exit code 1
```

This template uses ubuntu-latest, so I tried to update the awscli at the beginning

```
    steps:
    - name: Update
      run: |
        pip install wheel
        pip install --upgrade awscli
```
Got successfully executed:

```
Successfully installed awscli-1.17.0
```

But the error persists.

### PR DESCRIPTION
**Pull request by clareliguori**
Fixes #22

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: dist/index.js [hunk 1]
```diff
@@ -137,6 +137,15 @@ const CODE_DEPLOY_MAX_WAIT_MINUTES = 360;  // 6 hours
 const CODE_DEPLOY_MIN_WAIT_MINUTES = 30;
 const CODE_DEPLOY_WAIT_DEFAULT_DELAY_SEC = 15;
 
+// Attributes that are returned by DescribeTaskDefinition, but are not valid RegisterTaskDefinition inputs
+const IGNORED_TASK_DEFINITION_ATTRIBUTES = [
```
Comment (allisaurus) [inline dist/index.js]: why is this and `removeIgnoredAttributes` duplicated here and in `index.js`? Is this generated from the latter?

Comment (allisaurus) [reply dist/index.js]: offline: confirmed this is the case.
